### ISSUE TITLE
chk keys not returning anything 

### ISSUE THREAD

**Issue by TomHarkness** [RfidResearchGroup/proxmark3#1] opened 2018-08-13 14:20 UTC
**issuing hf mf chk keys returns nothing**

No output from hf mf chk command, "hf mf chk *1 ?" returns no keys and executes in no time and returns: Time in checkkeys: 0 seconds

RDV3 and pm3-easy board, same issue.

**Expected behavior**

**Screenshots**

**OS X High Sierra**

pm3 --> hw ver

Proxmark3 RFID instrument

 [ CLIENT ]
 client: iceman build for RDV40 with flashmem; smartcard;

 [ ARM ]
 bootrom: iceman/master/ 2018-08-13 21:53:19
      os: iceman/master/ 2018-08-13 21:53:22

 [ FPGA ]
 LF image built for 2s30vq100 on 2017/10/25 at 19:50:50
 HF image built for 2s30vq100 on 2018/ 8/10 at 11:48:34

 [ Hardware ]
  --= uC: AT91SAM7S512 Rev B
  --= Embedded Processor: ARM7TDMI
  --= Nonvolatile Program Memory Size: 512K bytes, Used: 235171 bytes (45) Free: 289117 bytes (55)
  --= Second Nonvolatile Program Memory Size: None
  --= Internal SRAM Size: 64K bytes
  --= Architecture Identifier: AT91SAM7Sxx Series
  --= Nonvolatile Program Memory Type: Embedded Flash Memory

pm3 --> hw status
#db# Memory
#db#   BIGBUF_SIZE.............40000
#db#   Available memory........40000
#db# Tracing
#db#   tracing ................0
#db#   traceLen ...............103
#db# Currently loaded FPGA image
#db#   mode.................... LF image built for 2s30vq100 on 2017/10/25 at 19:50:50
#db# Flash memory
#db#   init....................FAIL
#db# Smart card module (ISO 7816)
#db#   version.................FAILED
#db# LF Sampling config
#db#   [q] divisor.............95 (125 KHz)
#db#   [b] bps.................8
#db#   [d] decimation..........1
#db#   [a] averaging...........Yes
#db#   [t] trigger threshold...0
#db# USB Speed
#db#   Sending USB packets to client...
hw tune
#db#   Time elapsed............1500ms
#db#   Bytes transferred.......806400
#db#   USB Transfer Speed PM3 -> Client = 537600 Bytes/s
#db# Various
#db#   MF_DBGLEVEL.............1
#db#   ToSendMax...............39
#db#   ToSendBit...............8
#db#   ToSend BUFFERSIZE.......2308
#db# Installed StandAlone Mods
#db#    LF HID26 standalone - aka SamyRun (Samy Kamkar)
pm3 --> hw tune

[=] measuring antenna characteristics, please wait...

...

[+] LF antenna: 46.17 V - 125.00 kHz
[+] LF antenna: 28.32 V - 134.00 kHz
[+] LF optimal: 49.43 V - 126.32 kHz
[+] LF antenna is OK

[+] HF antenna: 33.85 V - 13.56 MHz
[+] HF antenna is OK

[+] Displaying LF tuning graph. Divisor 89 is 134khz, 95 is 125khz.

**Additional context**

**Comment by iceman1001** [comment] 2018-08-13 20:40
Confirmed,  it was because of the fix for the other issue. you raised...

I pushed fix.

**Closed** 2018-08-13 20:39 UTC
