### ISSUE TITLE
Using hf 14b sim -- not working

### ISSUE THREAD

**Issue by fmsec** [RfidResearchGroup/proxmark3#2002] opened 2023-06-02 16:56 UTC
***Things to try before submitting bug report***
read the [troubleshooting guide](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Installation_Instructions/Troubleshooting.md)

***Compilation problems***
Try compiling with verbose.  `make VERBOSE=1` with main makefile or `make V=1` with cmake.

***flashing problems***
Have you followed the instructions properly?  ie,  flashed bootrom seperately first if you are going from Offical repo to Iceman repo.

-

**The issue**
We are using _hf 14b sim -u 11AA33BB_ with various readers that are ISO14443 type B capable, but it does not work. 

We tried OMNIKEY, and ACRs, various models

**Question**
Any recommendations on the ISO-14443 typeB readers that this simulation works with?

**Comment by iceman1001** [comment] 2023-08-29 19:28
Duplicate of: 

https://github.com/RfidResearchGroup/proxmark3/issues/1652

**Closed by iceman1001** 2023-08-29 19:28 UTC
